name: quiropractico_front
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  # Gestión de estado
  provider: ^6.1.1
  # Rutas y Navegación Web
  go_router: ^13.0.0
  # Conexión HTTP potente
  dio: ^5.4.0
  # Guardar token en local
  shared_preferences: ^2.2.2
  # Fuentes
  google_fonts: ^6.1.0
  # Formateo de fechas
  intl: ^0.19.0
  # Iconos
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_calendar: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
